@startmindmap

* Unit2
-- topic 
--- The general subject of a text.
--- Words or phrases
--- Be found in title

-- main point
--- Main idea
--- Import thought about a topic
--- Usually stated in one sentence

-- supporting details
--- Specific facts, reasons, examples or other kinds of information
--- Used to support the main points

++ body paragraphs
+++ Support the main point in your thesis statement
+++ Ideas in yours paragraphs should relate back to the thesis statement

+++ features
++++ The main point of the paragraphs expressed clearly.
++++ Definition of key terms(if necessary or not defined before)
++++ examples or other supporting evidence
++++ Comment on or evaluation of the main points
+++ How to evaluate a body paragraphs?

++ paragrasing
+++ How to paragrasing?
++++ three methods
++++ four things can’t be changed

+++ Characteristics of a good paraphrase
+++ Techniques used to Paraphrase
++++ Use appropriate synonyms
++++ Change the sentence type
++++ Change the voice from active to passive or from passiv e to active.
++++ Change the part of speech.

@endmindmap
